src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
  
     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity=Marker::class, inversedBy="events", cascade={"persist", "remove"})
     */
    private $marker_id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="organized_events")
     */
    private $organizer_id;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="participated_events")
     */
    private $participant_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="float")
     */
    private $lat;

    /**
     * @ORM\Column(type="float")
     */
    private $lng;


    public function __construct()
    {
        $this->participant_id = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getMarkerId(): ?Marker
    {
        return $this->marker_id;
    }

    public function setMarkerId(?Marker $marker_id): self
    {
        $this->marker_id = $marker_id;

        return $this;
    }

    public function getOrganizerId(): ?User
    {
        return $this->organizer_id;
    }

    public function setOrganizerId(?User $organizer_id): self
    {
        $this->organizer_id = $organizer_id;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getParticipantId(): Collection
    {
        return $this->participant_id;
    }

    public function addParticipantId(User $participantId): self
    {
        if (!$this->participant_id->contains($participantId)) {
            $this->participant_id[] = $participantId;
        }

        return $this;
    }

    public function removeParticipantId(User $participantId): self
    {
        if ($this->participant_id->contains($participantId)) {
            $this->participant_id->removeElement($participantId);
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, [
                'required' => true
            ])
            ->add('address', null, [
                'required' => true
            ])
            ->add('description', null, [
                'required' => true
            ])
            ->add('date', DateType::class, [
                'required' => true,
                'data'   => new \DateTime(),
                'attr'   => ['min' => ( new \DateTime("now") )->format('Y-m-d H:i:s')]
            ])
            // ->add('marker_id')
            // ->add('organizer_id')
            // ->add('participant_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
            'csrf_protection' => true,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;


use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;


/**
 * Class EventController
 * 
 * * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/map", name="event_map")
     */
    public function displayMap()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $repository = $this->getDoctrine()->getRepository(Event::class);
        $events = $repository->findAll();
        $return = array();
        foreach ($events as $key => $value) {
            array_push($return, [$value, $this->generateUrl('event_join', ['id' => $value->getId()], UrlGeneratorInterface::ABSOLUTE_URL)]);
        }

        return $this->render('event/map.html.twig', [
            'controller_name' => 'EventController',
            'events' => $return
        ]);
    }

    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $repository = $this->getDoctrine()->getRepository(Event::class);
        $events = $repository->findAll();
        $return = array();
        foreach ($events as $key => $value) {

            foreach ($value->getParticipantId() as $key2 => $value2) {
                if ($value2 == $this->getUser()) {

                    array_push($return, $value);
                }
            }
        }
        return $this->render('event/index.html.twig', [
            "myEvents" => $return,
            'events' => $events
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();

        if ($user != null) {
            if ($user->getIsGodParent() != true) {
                $this->addFlash(
                    'error',
                    'Vous devez être connecté en tant que Buddy pour avoir accès à cette page.'
                );
                return $this->redirectToRoute('app_index');
            }
        }

        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            ////////////////////////////////////////////////////////
            $req = $request->request->get("event");
            // // url encode the address
            $address = urlencode($req["address"]);

            // google map geocode api url
            $url = "http://api.positionstack.com/v1/forward?access_key=56ebc1cf8ff6963df4f34386870621f4&query={$address}";

            // get the json response
            $resp_json = file_get_contents($url);

            // decode the json
            $resp = json_decode($resp_json, true);
            // response status will be 'OK', if able to geocode given address 
            if ($resp['data'] != null) {
                $lat = $resp['data'][0]["latitude"];
                $lon = $resp['data'][0]["longitude"];
                $event->setLat($lat);
                $event->setLng($lon);
                ///////////////////////////////////////////////////
                $event->setOrganizerId($this->getUser());

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($event);
                $entityManager->flush();

                $this->addFlash('success', "L'évènement a bien été créé.");
                return $this->redirectToRoute('event_index');
            }
            else{
                $this->addFlash('error', "Impossible de trouver l'adresse");
                return $this->redirectToRoute('event_new');
            }
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event): Response
    {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');


        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();

        if ($user != null) {
            if ($user->getId() != $event->getOrganizerId()->getId()) {
                $this->addFlash(
                    'error',
                    "Vous n'avez pas accès à cette page."
                );
                return $this->redirectToRoute('app_index');
            }
        }


        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', "L'évènement a bien été modifié.");
            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("join/{id}", name="event_join", methods={"GET"})
     */
    public function join(Request $request, int $id): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $entityManager = $this->getDoctrine()->getManager();
        $repository = $entityManager->getRepository(Event::class);

        $user = $this->getUser();

        if ($user != null) {
            $event = $repository->findOneBy(["id" => $id]);
            if ($event != null) {
                if ($user->getId() == $event->getOrganizerId()->getId()) {
                    $this->addFlash(
                        'error',
                        "Vous ne pouvez pas rejoindre cet événement."
                    );
                    return $this->redirectToRoute('app_index');
                } else {
                    $me = $event->getParticipantId()->filter(function ($element) {
                        return $element->getId() == $this->getUser()->getId();
                    });
                    if ($me->count() < 1) {
                        $event->addParticipantId($user);

                        $entityManager->flush($event);
                        $this->addFlash(
                            'success',
                            "Vous avez rejoint l'événement"
                        );
                    } else {
                        $entityManager->flush($event);
                        $this->addFlash(
                            'error',
                            "Vous avez déjà rejoint l'événement"
                        );
                    }

                    return $this->redirectToRoute('event_index');
                }
            } else {
                $this->addFlash(
                    'error',
                    "Il semble que cet événement est inexistant."
                );
                return $this->redirectToRoute('app_index');
            }
        }
        $this->addFlash(
            'error',
            "Une erreur s'est produite"
        );
        return $this->redirectToRoute('app_index');
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
    /**
     * @Route("/{id}", name="event_leave")
     */
    public function leave(Request $request, Event $event): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if ($this->isCsrfTokenValid('leave' . $event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $repository = $entityManager->getRepository(Event::class);
            $myEvent = $repository->findOneBy(['id' => $event->getID()]);
            $myEvent->removeParticipantId($this->getUser());
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet évènement ?');">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button>Supprimer</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button >{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/_leave_event_form.html.twig
<form method="post" action="{{ path('event_leave', {'id': event.id}) }}" onsubmit="return confirm('Voulez-vous vraiment quitter cet évènement ?');">
    <input type="hidden" name="_method" value="leave">
    <input type="hidden" name="_token" value="{{ csrf_token('leave' ~ event.id) }}">
    <button>Quitter</button>
</form>

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un évènement{% endblock %}

{% block body %}
    {# TODO: add margin entre nav et body #}
    <div style="height: 100px;"></div>
    {{ form_start(form) }}
    <div id="register">
        <div class="mb-5">
            <h1>Modifier un évènement
            </h1>
            <hr>
        </div>

        <div class="circle-right"></div>
        <div class="container">
        <div class="row form-group">
            <div class="col-xl-6">
                <div class="mb-xl-5 mb-2">
                    {{ form_label(form.name, "Nom de l'évènement :") }}
                    {{ form_widget(form.name, {
                        'attr': {'placeholder': "Nom de l'évènement", 'class' : 'form-control'}
                    }) }}
            </div>
                <div class="mb-2 mb-xl-0">
                    {{ form_label(form.address, "Adresse :") }}
                    {{ form_widget(form.address, {
                        'attr': {'placeholder': "Adresse", 'class' : 'form-control'}
                    }) }}
                </div>
            </div>
            <div class="col-xl-6">
                <div class="mb-xl-5 mb-2">
                    {{ form_label(form.description, "Description :") }}
                    {{ form_widget(form.description, {
                        'attr': {'placeholder': "Description", 'class' : 'form-control'}
                    }) }}
                </div>
                <div class="mb-2 mb-xl-0">
                    {{ form_label(form.date, "Date : ") }}
                    {{ form_widget(form.date, {
                        'attr': {'placeholder': "Date"}
                    }) }}
                </div>
            </div>
        </div>
        </div>


        <div class="row container-button mt-5">
            <div class="edit-profil">
                <button class="btn-l green">Valider</button>
            </div>
        </div>
        <div class="circle-left"></div>
    </div>
    {{ form_end(form) }}

{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes évènements{% endblock %}

{% block body %}

    <div id="eventIndex">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success" role="success">
                {{message}}
            </div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger" role="danger">
                {{message}}
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-12">
                <h1>Mes évènements rejoints</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
            {% if myEvents|length > 0 %}
                {% for event in myEvents %}
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h3>{{ event.name }}</h3>
                                <p><span class="gras">Organisateur :</span> {{ event.name }}</p>
                                <p><span class="gras">Description :</span> {{ event.description }}</p>
                                <p><span class="gras">Adresse :</span> {{ event.address }}</p>
                                <p><span class="gras">Date :</span> {{ event.date ? event.date|date('Y-m-d') : '' }}</p>
                                <br>
                                <div class="mt-2 text-right">
                                    {{ include('event/_leave_event_form.html.twig') }}
                                </div>
                            </div>
                        </div>
                {% endfor %}
            {% else %}
                <p>Pas d'évènements rejoints</p>
                <button href="{{ path('event_map') }}">Rejoindre un évènement</button>
            {% endif %}
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12">
                <h1>Mes évènements créés</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                {% set i = 0 %}
                {% for event in events %}
                    {% if app.user == event.organizerId %}
                        {% set i = i + 1 %}
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h3>{{ event.name }}</h3>
                                <p><span class="gras">Organisateur :</span> {{ event.name }}</p>
                                <p><span class="gras">Description :</span> {{ event.description }}</p>
                                <p><span class="gras">Adresse :</span> {{ event.address }}</p>
                                <p><span class="gras">Date :</span> {{ event.date ? event.date|date('Y-m-d') : '' }}</p>
                                <a href="{{ path('event_edit', {'id': event.id}) }}">Modifier</a>
                                <br>
                                <div class="mt-2 text-right">
                                    {{ include('event/_delete_form.html.twig') }}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                {% if i == 0 %}
                    <p>Pas d'évènements encore créés</p>
                    <button href="{{ path('event_new') }}">Créer un évènement</button>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/event/map.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rejoindre un évènement
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('leaflet') }}
{% endblock %}

{% block body %}
{% for message in app.flashes('error') %}
                    	<div class="alert alert-success" role="alert">
                        	{{message}}
                    	</div>
                	{% endfor %}
					{% for message in app.flashes('success') %}
                    	<div class="alert alert-success" role="alert">
                        	{{message}}
                    	</div>
                	{% endfor %}
		<div id="map-display">
		<div class="row">
			<div class="col-xl-4 p-4">
				<h1>Rejoindre un évènement
					<hr></h1>
				<ul class="list-group">

					{% for event in events %}
						{% set entity = event[0] %}
						{% set url = event[1] %}

						<li class="list-group-item">
							<div class="row">
								<div class="col-7">{{ entity.address }}
								</div>
								<div class="col-5">
									<a type="button" href="{{ url }}" class="btn btn-outline-primary float-right">Rejoindre
								</a>
								</div>
							</div>
						</li>


			{% endfor %}
		</ul>
</div>

			<div class="col-xl-8">
				<div id="map"></div>
			</div>
		</div>
		<div class="row" >
			<div class="col-xl-4 p-4">

			</div>

		</div>

	</div>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script>

		var markers = [];
		{% for event in events %}
		{% set entity = event[0] %}
		{% set url = event[1] %}

		 markers.push([{{ entity.id }},"{{ entity.address }}", {{ entity.lat }}, {{ entity.lng }}, "{{url}}"]) 
		{% endfor %}
		{# console.log(markers) #}
	</script>
	{{ encore_entry_script_tags('map') }}


{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un évènement
{% endblock %}

{% block body %}
	{# TODO: add margin entre nav et body #}
	<div style="height: 100px;"></div>
	{{ form_start(form) }}
	<div id="register">
		<div class="mb-5">
			<h1>Créer un évènement
			</h1>
			<hr>
		</div>

		<div class="circle-right"></div>
		<div class="container">
			{% for message in app.flashes('success') %}
				<div class="alert alert-success" role="success">
					{{message}}
				</div>
			{% endfor %}
			{% for message in app.flashes('error') %}
				<div class="alert alert-danger" role="danger">
					{{message}}
				</div>
			{% endfor %}
			<div class="row form-group">
				<div class="col-xl-6">
					<div class="mb-xl-5 mb-2">
						{{ form_label(form.name, "Nom de l'évènement :") }}
						{{ form_widget(form.name, {
                        'attr': {'placeholder': "Nom de l'évènement", 'class' : 'form-control'}
                    }) }}
					</div>
					<div class="mb-2 mb-xl-0">
						{{ form_label(form.address, "Adresse :") }}
						{{ form_widget(form.address, {
                        'attr': {'placeholder': "Adresse", 'class' : 'form-control'}
                    }) }}
					</div>
				</div>
				<div class="col-xl-6">
					<div class="mb-xl-5 mb-2">
						{{ form_label(form.description, "Description :") }}
						{{ form_widget(form.description, {
                        'attr': {'placeholder': "Description", 'class' : 'form-control'}
                    }) }}
					</div>
					<div class="mb-2 mb-xl-0">
						{{ form_label(form.date, "Date : ") }}
						{{ form_widget(form.date, {
                        'attr': {'placeholder': "Date"}
                    }) }}
					</div>
				</div>
			</div>
		</div>


		<div class="row container-button mt-5">
			<div class="edit-profil">
				<button class="btn-l green">Créer un évènement</button>
			</div>
		</div>
		<div class="circle-left"></div>
	</div>
	{{ form_end(form) }}

{% endblock %}
{% block javascripts %}
{{ parent() }}
	<script>
		// import
import {OpenStreetMapProvider} from 'leaflet-geosearch';

// setup
const provider = new OpenStreetMapProvider();

// search
const results = await provider.search({query: input.value});
	</script>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ event.address }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ event.date ? event.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('event_index') }}">back to list</a>

    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}