src/Entity/Channel.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\ChannelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChannelRepository::class)
 */
class Channel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $name;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="author_channel")
     */
    private $author_id;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="channel", orphanRemoval=true)
     */
    private Collection $messages;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="participant_channel")
     */
    private $get_participant;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthorId(): ?User
    {
        return $this->author_id;
    }

    public function setAuthorId(?User $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setChannel($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getChannel() === $this) {
                $message->setChannel(null);
            }
        }

        return $this;
    }

    public function getGetParticipant(): ?User
    {
        return $this->get_participant;
    }

    public function setGetParticipant(?User $get_participant): self
    {
        $this->get_participant = $get_participant;

        return $this;
    }
}

src/Entity/User.php
<?php
namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use http\Exception;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\EmailValidator;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "'{{ value }}' n'est pas une adresse mail valide."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Regex("/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{6,})^/")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("^(0|(\\+33)|(0033))[1-9][0-9]{8}^", message="Numéro de téléphone invalide")
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $school;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_connected;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_godparent = false;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $spoken_language = ['fr'];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $language_to_learn = ['fr'];


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     *
     * @Vich\UploadableField(mapping="buddy_images", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_godson = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="organizer_id", cascade={"persist", "remove"})
     */
    private $organized_events;

    /**
     * @ORM\OneToMany(targetEntity=Channel::class, mappedBy="author_id", cascade={"persist", "remove"})
     */
    private $author_channel;

    /**
     * @ORM\ManyToMany(targetEntity=Event::class, mappedBy="participant_id")
     */
    private $participated_events;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="author", cascade={"persist", "remove"})
     */
    private $messages;
    
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isBanned;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isReported;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      min = 10,
     *      max = 200,
     *      minMessage = "Votre message est trop court (minimum 10 caractères.",
     *      maxMessage = "Votre message est trop long (maximum 200 caractères)."
     * )
     */
    private $reportReason;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $blacklist = [];
    
    /**
     * @ORM\OneToMany(targetEntity=Channel::class, mappedBy="get_participant", cascade={"persist", "remove"})
     */
    private $participant_channel;

    /**
     * @ORM\OneToMany(targetEntity=Friendship::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $friends;

    /**
     * @ORM\OneToMany(targetEntity=Friendship::class, mappedBy="friend", cascade={"persist", "remove"})
     */
    private $friendsWithMe;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     */
    private $reportedBy;



    public function __construct()
    {
        $this->organized_events = new ArrayCollection();
        $this->participated_events = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->participant_channel = new ArrayCollection();
        $this->friends = new ArrayCollection();
        $this->friendsWithMe = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getSchool(): ?string
    {
        return $this->school;
    }

    public function setSchool(string $school): self
    {
        $this->school = $school;

        return $this;
    }

    public function getIsConnected(): ?bool
    {
        return $this->is_connected;
    }

    public function setIsConnected(bool $is_connected): self
    {
        $this->is_connected = $is_connected;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsGodparent(): ?bool
    {
        return $this->is_godparent;
    }

    public function setIsGodparent(?bool $is_godparent): self
    {
        $this->is_godparent = $is_godparent;

        return $this;
    }

    public function getSpokenLanguage(): ?array
    {
        return $this->spoken_language;
    }

    public function setSpokenLanguage(?array $spoken_language): self
    {
        $this->spoken_language = $spoken_language;

        return $this;
    }

    public function getLanguageToLearn(): ?array
    {
        return $this->language_to_learn;
    }

    public function setLanguageToLearn(?array $language_to_learn): self
    {
        $this->language_to_learn = $language_to_learn;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getIsGodson(): ?bool
    {
        return $this->is_godson;
    }

    public function setIsGodson(?bool $is_godson): self
    {
        $this->is_godson = $is_godson;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getOrganizedEvents(): Collection
    {
        return $this->organized_events;
    }

    public function addOrganizedEvent(Event $organizedEvent): self
    {
        if (!$this->organized_events->contains($organizedEvent)) {
            $this->organized_events[] = $organizedEvent;

src/Form/ChannelType.php
<?php

namespace App\Form;

use App\Entity\Channel;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class ChannelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // peut-être ajouter un champs avec l'auteur
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Channel::class,
            'csrf_protection' => true,
        ]);
    }
}

templates/channel/chat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chat{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row pt-5">
            <h1>
                {% if (app.user == channel.authorId) %}
                    <a href="/messagerie/{{ channel.getParticipant.id }}">
                        <span>{{ channel.getParticipant.firstName }} {{ channel.getParticipant.lastName }}</span>
                    </a>
                    {% set userProfile = channel.getParticipant.id %}
                {% endif %}
                {% if (app.user == channel.getParticipant) %}
                <a href="/messagerie/{{ channel.authorId.id }}">
                    <span>{{ channel.authorId.firstName }} {{ channel.authorId.lastName }} </span>
                </a>
            </h1>
            {% set userProfile = channel.authorId.id %}
            {% set connected = false %}
            {% for friendship in friendships %}
                {% if friendship.user.id == app.user.id and friendship.friend.id == userProfile and friendship.hasBeenHelpful == true %}
                    <div>
                        <a class="btn btn-danger ml-5" href="{{ path('friendship_delete_id', {'id': friendship.id}) }}">
                            Retirer cet ami
                        </a>
                    </div>

                    {% set connected = true %}
                {% endif %}
            {% endfor %}
            {% if not connected %}
                <div>
                    <a class="btn btn-primary ml-5" href="{{ path('friendship_new_id', {'id': channel.authorId}) }}">
                        Ajouter en ami
                    </a>
                </div>

            {% endif %}
            {% endif %}


        </div>

        <div class="container" style="height: 600px">
            <div id="container-message" class="container bg-light h-75 overflow-auto test">
                {% for message in messages %}
                    {% if app.user == message.author %}
                        <div class="row w-75 float-right">
                            <b>{{ message.author.firstname }} {{ message.author.lastname }}</b>
                            <p class="alert alert-info w-100">
                                {{ message.content }}
                            </p>
                        </div>
                    {% else %}
                        <div class="row w-75 float-left">
                            <b><a href="/messagerie/{{ message.author.id }}">{{ message.author.firstname }} {{ message.author.lastname }}
                                </a>

                                </p>
                            </b>
                            <p class="alert alert-success w-100">
                                {{ message.content }}
                            </p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div >
                <form id="form" class="container row">
                    <input id="message" class="input-group-text col-sm-9" placeholder="Message" type="text" />
                    <button id="btnEnvoi" type="submit" class="ml-2" >Envoyer</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
{{ parent() }}
    <script>

        let chatDiv = document.querySelector('.test');
        chatDiv.scrollTop = chatDiv.scrollHeight; // On souhaite scroller toujours jusqu'au dernier message du chat
        let form = document.getElementById('form');
        function handleForm(event) {
              event.preventDefault(); // Empêche la page de se rafraîchir après le submit du formulaire
        }
        form.addEventListener('submit', handleForm);
        const submit = document.getElementById('btnEnvoi');
        submit.onclick = e => { // On change le comportement du submit
            console.log("fefefef")
            const message = document.getElementById('message'); // Récupération du message dans l'input correspondant
            const data = { // La variable data sera envoyée au controller
                'content': message.value, // On transmet le message...
                'channel': {{ channel.id }} // ... Et le canal correspondant
            }
            console.log(data); // Pour vérifier vos informations
            //console.log("clique ici !!")
            fetch('/message', { // On envoie avec un post nos datas sur le endpoint /message de notre application
                method: 'POST',
                body: JSON.stringify(data) // On envoie les data sous format JSON
            }).then((response) => {
                message.value = '';
                console.log(response);
                //window.location.reload();
            });
        }
        var interval = 4000;
        var globalMessages = [];
        var contactName = "";
        {% for message in messages %}
        globalMessages.push([{{ message.id }}, {{ message.author.id }},"{{ message.content }}",new Date("{{ message.createdAt|date('d-m-Y H:i:s') }}")])
        {% endfor %}
        {% if app.user.id == channel.authorId.id %}
        contactName = "{{ channel.getParticipant.firstName  }} {{ channel.getParticipant.lastName  }}"
        {% else %}
        contactName = "{{ channel.authorId.firstName }} {{ channel.authorId.lastName }}"
        {% endif %}
        function makeRequest() {
            httpRequest = new XMLHttpRequest();
            if (!httpRequest) {
                alert('Abandon :( Impossible de créer une instance de XMLHTTP');
                return false;
            }
            var data = new FormData();
            data.append('date', interval);
            data.append('id',"{{ channel.id }}")
            httpRequest.onreadystatechange = function () {

                if (httpRequest.readyState === XMLHttpRequest.DONE) {
                    if (httpRequest.status === 200) {
                        let datas = JSON.parse(httpRequest.responseText);
                        let containerMessage = document.getElementById('container-message');
                        globalMessages.forEach((item,index)=>{
                            datas = datas.filter(dat => dat[0] > item[0]);
                        });

                        datas.forEach((item,index)=>{
                            globalMessages.push(item);
                            if(item[1] == {{ app.user.id }})
                            {
                                containerMessage.innerHTML += `
                            <div class="row w-75 float-right">
                                <b>` + "{{ app.user.firstname }} {{ app.user.lastname }}" + `</b>
                                <p class="alert alert-info w-100">
                                   `+item[2]+`
                                </p>
                            </div>`
                            }
                            else{
                                containerMessage.innerHTML += `<div class="row w-75 float-left">
                                <b><a href="/messagerie/` + item[1] + `">
                                    </a>` + contactName + `</p>
                                </b>
                                <p class="alert alert-success w-100">
                                   `+item[2]+`
                                </p>
                            </div>`
                            }

                        })
                        datas = [];
                        let chatDiv = document.querySelector('.test');
                        chatDiv.scrollTop = chatDiv.scrollHeight;
                        setTimeout(makeRequest, interval);
                    } else {
                    }
                }
            };
            httpRequest.open('POST', "{{ path('message_check') }}");
            httpRequest.send(data);
        }
        setTimeout(makeRequest, interval);

    </script>
{% endblock %}

templates/channel/index.html.twig
{# templates/channel/index.html.twig #}
{% extends 'base.html.twig' %}  
  
{% block title %}Messagerie{% endblock %}  
  
{% block body %}  
  
<div class="container" style="margin-top: 100px">

    {% for message in app.flashes('noticeGood') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('noticeDisconnect') %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
{% endfor %}
    {% set x = [] %}
    {% set y = 0 %}
    {% for friendship in friendships %}
        {% if app.user == friendship.user and friendship.hasBeenHelpFul == true %}
            {% set y = y + 1 %}
            {% set x = x|merge({(y): friendship}) %}
        {% endif %}
    {% endfor %}

    {% if x|length > 0 %} 
    <h2>Mes amis</h2>
        <table class="table table-striped">  
            <tbody>  
            {% for channel in channels %}  
                {% for user in x %} 
                    {% if user.user.id == channel.getParticipant.id and user.friend.id == channel.getAuthorId.id %}
                    <tr class="">  
                        <th>
                            {% if (user.friend.id == channel.getAuthorId.id) %}
                                <span>{{ channel.authorId.firstName }} {{ channel.authorId.lastName }}</span>
                            {% endif %}
                            <a class="btn btn-primary float-right" href="{{ path('chat', {id: channel.id}) }}">Discuter</a>
                        </th>  
                    </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}  
            </tbody>  
        </table>  
    {% endif %}

    {% set i = 0 %}
    {% for channel in channels %}
        {% if (app.user == channel.authorId) or (app.user == channel.getParticipant) %}
         {% set i = i + 1 %}
        {% endif %}
    {% endfor %}
    
    {% if i > 0 %} 
        <h2>Mes conversations</h2>
        <table class="table table-striped">  
            <tbody>  
            {% for channel in channels %}
                {% if (app.user == channel.authorId) or (app.user == channel.getParticipant) %}
                <tr class="">  
                    <th>
                        {% if (app.user == channel.authorId) %}
                            <span>{{ channel.getParticipant.firstName }} {{ channel.getParticipant.lastName }}</span>
                        {% endif %}
                        {% if (app.user == channel.getParticipant) %}
                            <span>{{ channel.authorId.firstName }} {{ channel.authorId.lastName }}</span>
                        {% endif %}
                        <a class="btn btn-primary float-right" href="{{ path('chat', {id: channel.id}) }}">Discuter</a>
                    </th>  
                </tr>
                {% endif %}

            {% endfor %}  
            </tbody>  
        </table>  
    {% else %}
        <div>
            <div class="alert alert-danger text-center">Aucune conversation trouvée.</div>
        </div>
    {% endif %}


</div>  
{% endblock %}

templates/channel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Channel{% endblock %}

{% block body %}
<div id="createChannel">

    <div class="container" >
    <div class="col-md-12 mx-auto text-center mt-5" data-aos="zoom-in" data-aos-offset="300" data-aos-easing="ease-in-sine">

        <h3>Souhaites-tu commencer à discuter avec <span class="text-dark"><u>{{ user.firstname }} {{ user.lastname }} ? </u><span></span></h3>
        <div class="row text-center">
        <div class="col-md-12 ">
            <div class="d-flex justify-content-center mt-3">
                <div class="mr-3">
                    <button class="btn-lg btn-danger">Annuler</button>
                </div>
                <div class="ml-5">
                    {{ form_start(form) }}
                    <button class="btn-lg">Oui, let's go !</button>
                    {{ form_end(form) }}
                </div>

            </div>
            </div>
        </div>
    </div>
        <img src="{{ asset('build/images/phonechat.jpg') }}" alt="phone chat" width="700"/>

    </div>
</div>
{% endblock %}