src/Entity/User.php
<?php
namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use http\Exception;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\EmailValidator;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "'{{ value }}' n'est pas une adresse mail valide."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Regex("/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{6,})^/")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("^(0|(\\+33)|(0033))[1-9][0-9]{8}^", message="Numéro de téléphone invalide")
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $school;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_connected;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_godparent = false;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $spoken_language = ['fr'];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $language_to_learn = ['fr'];


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     *
     * @Vich\UploadableField(mapping="buddy_images", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_godson = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="organizer_id", cascade={"persist", "remove"})
     */
    private $organized_events;

    /**
     * @ORM\OneToMany(targetEntity=Channel::class, mappedBy="author_id", cascade={"persist", "remove"})
     */
    private $author_channel;

    /**
     * @ORM\ManyToMany(targetEntity=Event::class, mappedBy="participant_id")
     */
    private $participated_events;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="author", cascade={"persist", "remove"})
     */
    private $messages;
    
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isBanned;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isReported;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      min = 10,
     *      max = 200,
     *      minMessage = "Votre message est trop court (minimum 10 caractères.",
     *      maxMessage = "Votre message est trop long (maximum 200 caractères)."
     * )
     */
    private $reportReason;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $blacklist = [];
    
    /**
     * @ORM\OneToMany(targetEntity=Channel::class, mappedBy="get_participant", cascade={"persist", "remove"})
     */
    private $participant_channel;

    /**
     * @ORM\OneToMany(targetEntity=Friendship::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $friends;

    /**
     * @ORM\OneToMany(targetEntity=Friendship::class, mappedBy="friend", cascade={"persist", "remove"})
     */
    private $friendsWithMe;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     */
    private $reportedBy;



    public function __construct()
    {
        $this->organized_events = new ArrayCollection();
        $this->participated_events = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->participant_channel = new ArrayCollection();
        $this->friends = new ArrayCollection();
        $this->friendsWithMe = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getSchool(): ?string
    {
        return $this->school;
    }

    public function setSchool(string $school): self
    {
        $this->school = $school;

        return $this;
    }

    public function getIsConnected(): ?bool
    {
        return $this->is_connected;
    }

    public function setIsConnected(bool $is_connected): self
    {
        $this->is_connected = $is_connected;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsGodparent(): ?bool
    {
        return $this->is_godparent;
    }

    public function setIsGodparent(?bool $is_godparent): self
    {
        $this->is_godparent = $is_godparent;

        return $this;
    }

    public function getSpokenLanguage(): ?array
    {
        return $this->spoken_language;
    }

    public function setSpokenLanguage(?array $spoken_language): self
    {
        $this->spoken_language = $spoken_language;

        return $this;
    }

    public function getLanguageToLearn(): ?array
    {
        return $this->language_to_learn;
    }

    public function setLanguageToLearn(?array $language_to_learn): self
    {
        $this->language_to_learn = $language_to_learn;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getIsGodson(): ?bool
    {
        return $this->is_godson;
    }

    public function setIsGodson(?bool $is_godson): self
    {
        $this->is_godson = $is_godson;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getOrganizedEvents(): Collection
    {
        return $this->organized_events;
    }

    public function addOrganizedEvent(Event $organizedEvent): self
    {
        if (!$this->organized_events->contains($organizedEvent)) {
            $this->organized_events[] = $organizedEvent;

templates/user/delete-account.html.twig
{% extends 'base.html.twig' %}

{% block title %}Confirmation suppression du compte
{% endblock %}

{% block body %}
    <div id="register">
        <div class="row register mt-sm-5">
            <div class="circle-right"></div>
            <div class="col-lg-12 col-sm-12 circle-parent" data-aos="fade-right">
                <h1>Êtes-vous sûr de supprimer votre compte ?
                    <hr></h1>
                <div class="mx-auto">
                    <a href="{{ path('user_delete', { 'id': app.user.id }) }}" class="hrefbutton">
                            Oui, je souhaite supprimer définitivement mon compte !
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/edit-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon mot de passe
{% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div id="register">
        <div class="row register mt-sm-5">
            <div class="circle-right"></div>
            <div class="col-lg-12 col-sm-12 circle-parent" data-aos="fade-right">
                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
                <h1>Modifier mon mot de passe<hr></h1>

                <div class="form-field mb-2">
                    <div class="col">
                        {{ form_row(form.oldPassword) }}
                    </div>
                </div>
                <div class="form-field">
                    <div class="col">
                        {{ form_row(form.newPassword) }}
                    </div>
                </div>
                <br>
                <button class="btn-lg green">Valider</button>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/user/edit-profile.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block title %}Profil
{% endblock %}
{% block body %}
	{{ form_start(formEditProfil) }}
	<div id="register">
		<div class="row register mt-sm-5">
			{% for message in app.flashes('message') %}
				<div class="alert alert-success" role="alert">
					{{message}}
				</div>
			{% endfor %}
			<div class="col-lg-12 col-sm-12" data-aos="fade-right">
				<div class="row">
					<div class="col">
						{% if new == false %}
							<h1>Bienvenue sur ton profil
								{{ app.user.firstname }}
								{{ app.user.lastname }}
								<hr></h1>
						{% else %}
							<h1>Complète ton profil
								{{ app.user.firstname }}
								{{ app.user.lastname }}
								<hr></h1>
						{% endif %}
					</div>
				</div>

				<div class="row form-group">
					<div class="col-lg-4 col-sm-12">
						<div class="row">
							<div class="col">

								<div class="row">
									{% if app.user.imageName == null %}
										<img name="profilImage" id="previewimg" src="{{ asset('build/images/profil.png') }}" style="max-height:240px;max-width:240px;"/>
									{% else %}
										<img id="pi" src="{{ vich_uploader_asset(app.user, 'imageFile') }}" alt="image" style="width: 205px; height:205px" />
									{% endif %}
								</div>
								<div class="row">
									{{ form_widget(formEditProfil.imageFile) }}
								</div>
							</div>
						</div>

						<div class="row form-group">
							<div class="col">
								{{ form_widget(formEditProfil.isGodparent) }}
								{{ form_label(formEditProfil.isGodparent, "Je souhaite parrainer ") }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col">
								{{ form_widget(formEditProfil.isGodson) }}
								{{ form_label(formEditProfil.isGodson, "Je veux être filleul") }}
							</div>
						</div>
					</div>

					<div class="col-lg-4 col-sm-12">
						<div class="row form-group">
							<div class="col edit-profil">

								<h5>Tes langues parlées :</h5>
								{# {{ form_label(formEditProfil.spokenLanguage, )}} #}
								{{ form_widget(formEditProfil.spokenLanguage, {
									'attr': {
										'class' : 'form-control multiselect-select2',
										'multiple':''
									}
								})
								}}
							</div>
							<br>
						</div>


						<div class="row form-goup mb-4">
							<div class="col edit-profil">
								<h5>Tes langues en apprentissage :</h5>
								{# {{ form_label(formEditProfil.languageToLearn, )}} #}
								{{ form_widget(formEditProfil.languageToLearn, {
									'attr': {
										'class' : 'form-control multiselect-select2',
										'multiple':''
									}
								})
								}}
							</div>
						</div>
					</div>

					<div class="col-lg-4 col-sm-12 ">
						<div class="row form-group">
							<div class="col">
								<div class="edit-profil">
									<h5>Ta description :</h5>
									{{ form_widget(formEditProfil.description, {
										'attr': {
											'placeholder': "Présente-toi et parles-nous de tes hobbies !",
											'class' : 'form-control',
											'style':'padding:20px;',
											'onkeyup':'countUpdate(this.value)'
										}
									})

									}}
								</div>
								<div class="row float-right">
									<p id="description-lenght">
										<small>
											<span id="charcount">{{ app.user.description|length }}</span>
											/ 600</small>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>

				{% if new == false %}
					<div class="row container-button">
						<div class="edit-profil">
							<button class="btn-l green">Valider mes modifications !</button>
						</div>
					</div>
				{% else %}
					<div class="row container-button">
						<div class="edit-profil">
							<button class="btn-l green">J'ai terminé !</button>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
	{{ form_end(formEditProfil) }}

{% endblock %}
{% block javascripts %}

	{{ encore_entry_script_tags('app') }}

{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification du profil de {{ app.user.firstname }}{% endblock %}

{% block body %}
	{{ form_start(form) }}
	<div id="register">
		<div class="row register mt-sm-5">
			<div class="circle-right"></div>
			<div class="col-lg-5 col-sm-12 circle-parent" data-aos="fade-right">
				<h1>Modifier mon compte
					<hr></h1>
				<div class="form-group row mt-5">
					<div class="col">
						{{ form_label(form.last_name, "Nom :") }}
						{{ form_widget(form.last_name, {
							'attr': {'placeholder': "Nom", 'class' : 'form-control'}
						}) }}
						<div class="form-error">
							{{ form_errors(form.last_name) }}
						</div>
					</div>
				</div>
				<div class="form-group row mt-5">
					<div class="col">
						{{ form_label(form.first_name, "Prénom :") }}
						{{ form_widget(form.first_name, {
							'attr': {'placeholder': "Prénom", 'class' : 'form-control'}
						}) }}
						<div class="form-error">
							{{ form_errors(form.first_name) }}
						</div>
					</div>
				</div>
				<div class="form-group row mt-5">
					<div class="col">
						{{ form_label(form.email, "Adresse mail :") }}
						{{ form_widget(form.email, {
							'attr': {'placeholder': "Adresse mail", 'class' : 'form-control'}
						}) }}
						<div class="form-error">
							{{ form_errors(form.email) }}
						</div>
					</div>
				</div>
			</div>

			<div class="col-lg-5 col-sm-12 mt-lg-n1 mt-sm-0 pt-lg-4 pt-sm-0" data-aos="fade-left" data-aos-once="true">
				<div class="mt-lg-5">
					<div class="form-group mt-lg-n2 mt-sm-0 row">
						<div class="col mt-lg-4">
							{{ form_label(form.school, "Ecole :") }}
							{{ form_widget(form.school, {
								'attr': {'placeholder': "Ecole", 'class' : 'form-control'}
							}) }}
							<div class="form-error">
								{{ form_errors(form.school) }}
							</div>
						</div>
					</div>
					<div class="form-group row mt-5">
						<div class="col">
							{{ form_label(form.phone_number, "Numéro de téléphone :") }}
							{{ form_widget(form.phone_number, {
								'attr': {'placeholder': "Numéro de téléphone", 'class' : 'form-control'}
							}) }}
							<div class="form-error">
								{{ form_errors(form.phone_number) }}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row container-button">
			<div class="">
				<button class="btn-l green">Valider mes modifications</button>
			</div>
		</div>
		<div class="circle-left"></div>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/user/forgot-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Mot de passe oublié
{% endblock %}

{% block body %}

	<div id="login">
		<div class="row">
			<div class="col-lg-7 col-sm-12">
				<div class="contenu" data-aos="fade-right" data-aos-offset="400">
					{% for message in app.flashes('error') %}
						<div class="alert alert-danger" role="alert">
							{{message}}
						</div>
					{% endfor %}
					{% for message in app.flashes('success') %}
						<div class="alert alert-success" role="alert">
							{{message}}
						</div>
					{% endfor %}

					<h1>Mot de passe oublié</h1>

					<form class="mt-5" method="POST" action="{{ path('user_forgot-password') }}">
						<div class="form-group row mt-5">
							<div class="col-lg-7">
								<label for="exampleInputEmail1">Adresse email :</label>
								<input type="email" class="form-control mt-2" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="toi@buddy.fr" name="email">
							</div>
						</div>
						<button type="submit" class="btn-lg">Valider</button>
					</form>
				</div>
			</div>

			<div class="col-lg-5 block-blue d-none d-lg-block d-xl-block">
				<div class="row">
					<div class="col-xl-12">
						<p>
							<a href="{{ path('app_register') }}">Pas encore de compte ?</a>
						</p>
					</div>
				</div>
				<img src="{{ asset('build/images/8576.png') }}" alt="logo studandbuddy" width="180px"/>
			</div>
		</div>
	</div>

	{% endblock %}

templates/user/reset-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau mot de passe
{% endblock %}

{% block body %}

	<div id="login">
		<div class="row">
			<div class="col-lg-7 col-sm-12">
				<div class="contenu" data-aos="fade-right" data-aos-offset="400">
					<h1>Nouveau mot de passe
						<hr></h1>
					<form class="mt-5" method="POST" action="{{ path('user_change_password',{'email':email ,'token':token}) }}" id="confirmform">
						<div class="form-group row mt-5">
							{% for message in app.flashes('error') %}
								<div class="alert alert-danger" role="alert">
									{{message}}
								</div>
							{% endfor %}
							<div class="col-lg-7">


								<label for="exampleInputEmail1">Nouveau mot de passe :</label>
								<input type="password" class="form-control mt-2" id="inputMdp" aria-describedby="emailHelp" placeholder="" name="inputMdp">
								<p>
									* Attention : votre mot de passe doit contenir au minimum 6 caractères avec au moins 1 majuscule, 1 minusculte, 1 chiffre et 1 caractère spécial.
								</p>

							</div>

							<div class="col-lg-7" style="margin-top:20px;">


								<label for="exampleInputEmail12">Confirmer nouveau mot de passe :</label>
								<input type="password" class="form-control mt-2" id="inputConfirmMdp" aria-describedby="emailHelp" placeholder="" name="inputConfirmMdp">

							</div>

						</div>

						<button id="confirmReset" class="btn-lg">Valider</button>
					</form>

					<p class="mt-3 d-block d-sm-block d-md-none">
						<a href="{{ path('app_register') }}">Pas encore de compte ?</a>
					</p>

				</div>
			</div>
			<div class="col-lg-5 block-blue d-none d-lg-block d-xl-block">
				<div class="row">
					<div class="col-xl-12">
						<p>
							<a href="{{ path('app_register') }}">Pas encore de compte ?</a>
						</p>
					</div>
				</div>
				<img src="{{ asset('build/images/8576.png') }}" alt="logo studandbuddy" width="180px"/>
			</div>
		</div>
	</div>
	{% endblock %}
	{% block javascripts %}
		{{ parent() }}
		{{ encore_entry_script_tags('reset-password') }}
{% endblock %}

templates/user/user-account.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil de {{ app.user.firstname }}
{% endblock %}

{% block body %}
	<div id="register">
		<div class="row register mt-sm-5">
			<div class="circle-right"></div>
			<div class="col-lg-5 col-sm-12 circle-parent" data-aos="fade-right">
				{% for message in app.flashes('message') %}
					<div class="alert alert-success" role="alert">
						{{message}}
					</div>
				{% endfor %}
				<h1>Mon compte
					<hr></h1>
				<div class="form-group row mt-5">
					<div class="col">
						<p><strong>Nom :</strong>
							{{ app.user.lastname|default('undefined') }}</p>
					</div>
				</div>
				<div class="form-group row mt-5">
					<div class="col">
						<p><strong>Prénom :</strong>
							{{ app.user.firstname|default('undefined') }}</p>
					</div>
				</div>
				<div class="form-group row mt-5">
					<div class="col">
						<p><strong>Adresse mail :</strong>
								{{ app.user.email|default('undefined') }}</p>
					</div>
				</div>
			</div>

			<div class="col-lg-5 col-sm-12 mt-lg-n1 mt-sm-0 pt-lg-4 pt-sm-0" data-aos="fade-left" data-aos-once="true">
				<div class="mt-lg-5">
					<div class="form-group mt-lg-n2 mt-sm-0 row">
						<div class="col mt-lg-4">
							<p><strong>École :</strong>
								{{ app.user.school|default('undefined') }}</p>
						</div>
					</div>
				</div>
				<div class="form-group row mt-5">
					<div class="col">
						<p><strong>Numéro de téléphone :</strong>
							{{ app.user.phonenumber|default('undefined') }}</p>
					</div>
				</div>
			</div>
		</div>


	<div class="row mb-4">
		<div class="mx-auto">
			<button href="{{ path('user_edit') }}">
			Modifier mes informations
			</button>
		</div>
	</div>
	<div class="row mb-4">
		<div class="mx-auto">
		<button href="{{ path('user_edit-password') }}">
				Modifier mon mot de passe
			</button>
		</div>
	</div>
	<div class="row">
		<div class="mx-auto">
			<a href="{{ path('user_delete_request') }}">
					Supprimer mon compte
				</a>
		</div>
	</div>
</div>
	{% endblock %}